const pieces=['♜','♞','♝','♛','♚','♝','♞','♜','♟','♟','♟','♟','♟','♟','♟','♟','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','♙','♙','♙','♙','♙','♙','♙','♙','♖','♘','♗','♕','♔','♗','♘','♖'];
const demoPlayers=[['Tomás Aguirre','TA','5.5','6','1','0','3','3','0'],['Mateo Ríos','MR','5.0','6','0','1','3','3','0'],['Lucía Velasco','LV','4.5','6','1','1','2','4','+2'],['Carla Méndez','CM','4.0','6','0','2','4','2','+2'],['Bruno Silva','BS','3.5','6','1','1','3','3','0'],['Sofía Paz','SP','3.0','6','0','0','2','4','+2']];
const adminMatches=[['01','Tomás Aguirre','TA','Bruno Silva','BS','En vivo','live','12:04','08:52'],['02','Carla Méndez','CM','Sofía Paz','SP','En vivo','live','10:31','11:45'],['03','Mateo Ríos','MR','Ana Torres','AT','Esperando jugador','wait','--','--'],['04','Lucía Velasco','LV','Mateo Ríos','MR','Resultado pendiente','pending','0:00','0:00'],['05','Diego Soto','DS','Julia Rey','JR','Resultado pendiente','pending','0:00','0:00'],['06','Nora Gil','NG','Pablo Cruz','PC','Resultado pendiente','pending','0:00','0:00'],['07','Eva León','EL','Iván Costa','IC','Revisar resultado','rejected','0:00','0:00']];
const history=[['12:36','Mesa 04 · resultado propuesto','Lucía Velasco propuso ½–½. Pendiente de aprobación.'],['12:10','Mesa 01 · movimiento 23','Tomás Aguirre movió Cf6.'],['11:48','Ronda 3 iniciada','8 mesas generadas. Emparejamientos equilibrados por color.'],['10 AGO','Ronda 2 cerrada','Todos los resultados revisados y clasificación actualizada.']];

function buildBoard(id){const el=document.getElementById(id); if(!el)return; el.innerHTML=''; pieces.forEach((p,i)=>{const cell=document.createElement('div');cell.textContent=p;el.appendChild(cell)});}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); const target=document.getElementById(name==='admin'?'admin-view':`view-${name}`); if(target)target.classList.add('active'); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); document.getElementById('page-title').textContent=name==='admin'?'Panel de administración':'Copa Primavera 2026';}
function renderStandings(){const body=document.getElementById('standings-body'); body.innerHTML=demoPlayers.map((p,i)=>`<tr class="${p[0].startsWith('Lucía')?'current':''}"><td>${i+1}</td><td><strong>${p[0]}</strong></td><td><strong>${p[2]}</strong></td><td>${p[3]}</td><td>${p[4]}</td><td>${p[5]}</td><td>${p[6]}</td><td>${p[7]}</td><td>${p[8]}</td></tr>`).join('');}
function renderHistory(){document.getElementById('history-list').innerHTML=history.map(h=>`<div class="timeline-item"><time>${h[0]}</time><div><strong>${h[1]}</strong><p>${h[2]}</p></div></div>`).join('');}
function renderAdmin(){const el=document.getElementById('admin-table');el.innerHTML='<div class="admin-row header"><span>Mesa</span><span>Blancas</span><span>Negras</span><span>Estado</span><span>Relojes</span><span>Acciones</span></div>'+adminMatches.map((m,i)=>`<div class="admin-row"><span><strong>${m[0]}</strong></span><div class="admin-player"><span class="avatar">${m[2]}</span>${m[1]}</div><div class="admin-player"><span class="avatar dark">${m[4]}</span>${m[3]}</div><span class="table-status ${m[6]}">${m[5]}</span><span>${m[7]} · ${m[8]}</span><div class="action-btns">${m[6]==='pending'||m[6]==='rejected'?`<button class="approve" data-approve="${i}">Aprobar</button><button class="reject" data-reject="${i}">Rechazar</button>`:'<span class="small-muted">Monitoreando</span>'}</div></div>`).join('');}
function openModal(){document.getElementById('modal-backdrop').hidden=false}
function closeModal(){document.getElementById('modal-backdrop').hidden=true}
document.addEventListener('click',e=>{const mode=e.target.closest('.mode-btn');if(mode){document.querySelectorAll('.mode-btn').forEach(b=>b.classList.remove('active'));mode.classList.add('active');showView(mode.dataset.mode==='admin'?'admin':'overview');document.querySelector('.nav-list').style.display=mode.dataset.mode==='admin'?'none':'';document.getElementById('primary-action').style.display=mode.dataset.mode==='admin'?'none':''}const nav=e.target.closest('[data-view]');if(nav&&!nav.classList.contains('mode-btn'))showView(nav.dataset.view);const target=e.target.closest('[data-view-target]');if(target)showView(target.dataset.viewTarget);if(e.target.id==='primary-action'||e.target.id==='registration-btn')openModal();if(e.target.id==='modal-close'||e.target.id==='modal-backdrop')closeModal();if(e.target.id==='submit-registration'){document.getElementById('registration-state').innerHTML='<div class="check-circle">✓</div><div><strong>Inscripción enviada</strong><span>Solicitud pendiente de aprobación</span></div>';closeModal();}if(e.target.dataset.approve){e.target.closest('.admin-row').querySelector('.table-status').textContent='Resultado aprobado';e.target.closest('.admin-row').querySelector('.table-status').className='table-status live';document.getElementById('pending-count').textContent='2';}if(e.target.dataset.reject){e.target.closest('.admin-row').querySelector('.table-status').textContent='Revisar resultado';e.target.closest('.admin-row').querySelector('.table-status').className='table-status rejected';}});
document.getElementById('reset-demo').addEventListener('click',()=>location.reload());
buildBoard('hero-board');buildBoard('large-board');renderStandings();renderHistory();renderAdmin();
